permalink:           pretty

# Setup
title:               홍씨
tagline:             'icehongssii(차가워홍씨)'s office'
description:         "Hey, hongssii"
url:                 http://icehongssii.github.io/
baseurl:             http://icehongssii.github.io/

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# paginate
paginate: 20
paginate_path: "/blog/page:num/"

# time agoß
jekyll_timeago:
  depth: 1

# About/contact
author:
  name:              icehongssii
  url:               http://github.com/icehongssii.github.io
  email:             icehongssii@gmail.com
