permalink:           pretty

# Setup
title:               '홍씨'
tagline:             'icehongssii'
description:         "icehongssii(차가워홍씨)'s office'"
url:                 http://icehongssii.github.io/
baseurl:             ''

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# paginate
paginate: 20
paginate_path: "/blog/page:num/"

# time ago
jekyll_timeago:
  depth: 1

# About/contact
author:
  name:              icehongssii
  url:               http://github.com/icehongssii
  email:             icehongssii@gmail.com
