permalink:           pretty

# Setup
title:               PERSIMMON
tagline:             '홍씨'
description:         "icehongssi's dev office"
url:                 http://icehongssii.github.io/
baseurl:             'http://icehongssii.github.io/'

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# time ago
jekyll_timeago:
  depth: 1

# About/contact
author:              icehongssii
  name:              icehongssii
  url:               http://github.com/icehongssii
  email:             icehongssii@gmail.com
